GET http://localhost:5000/allUsers

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###
GET http://localhost:3000/

###